### ISSUE TITLE
Unable to resolve some modules:

### ISSUE THREAD

**Issue by dangaresp** [abhiaiyer91/How-We-Redux-Todos#6]
Thank so much for your articles on Medium, you tutorials are aweosome!
I have this issue when run meteor.
```
daniel@4TW:~/meteor_apps/How-We-Redux-Todos$ meteor 
[[[[[ ~/meteor_apps/How-We-Redux-Todos ]]]]]  

=> Started proxy.                             
=> Started MongoDB.                           
                                              
Unable to resolve some modules:

  "./ReactInstrumentation" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactMount.js (web.browser)
  "./ReactDOMComponentTree" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/findDOMNode.js (web.browser)
  "./ReactFeatureFlags" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactMount.js (web.browser)
  "./DOMLazyTree" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactMount.js (web.browser)
  "./createMicrosoftUnsafeLocalFunction" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/setInnerHTML.js (web.browser)
  "./DOMNamespaces" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactDOMComponent.js (web.browser)
  "./ReactDOMInstrumentation" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/DOMPropertyOperations.js (web.browser)
  "./getVendorPrefixedEventName" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactBrowserEventEmitter.js (web.browser)
  "./ReactDOMComponentFlags" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactDOMComponent.js (web.browser)
  "./ReactNodeTypes" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactCompositeComponent.js (web.browser)
  "./ReactDOMEmptyComponent" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactDefaultInjection.js (web.browser)
  "./ReactDOMTreeTraversal" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactDefaultInjection.js (web.browser)
  "./SyntheticAnimationEvent" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/SimpleEventPlugin.js (web.browser)
  "./SyntheticTransitionEvent" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/SimpleEventPlugin.js (web.browser)
  "./ReactDOMContainerInfo" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactMount.js (web.browser)
  "./getNativeComponentFromComposite" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactDOM.js (web.browser)
  "../utils/warning" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react-redux/lib/components/connect.js (web.browser)
  "symbol-observable" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/redux/lib/createStore.js (web.browser)
  "./BreakView" in /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react-paginate/dist/PaginationListView.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save symbol-observable 
                                              
W20160428-17:06:56.581(-3)? (STDERR)          
W20160428-17:06:56.586(-3)? (STDERR) /home/daniel/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160428-17:06:56.588(-3)? (STDERR)            				throw(ex);
W20160428-17:06:56.588(-3)? (STDERR)            				      ^
W20160428-17:06:56.589(-3)? (STDERR) Error: Cannot find module './ReactInstrumentation'
W20160428-17:06:56.589(-3)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160428-17:06:56.590(-3)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160428-17:06:56.591(-3)? (STDERR)     at Module.require (module.js:364:17)
W20160428-17:06:56.592(-3)? (STDERR)     at require (module.js:380:17)
W20160428-17:06:56.593(-3)? (STDERR)     at Object.<anonymous> (/home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react/lib/ReactComponent.js:15:28)
W20160428-17:06:56.594(-3)? (STDERR)     at Module._compile (module.js:456:26)
W20160428-17:06:56.595(-3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160428-17:06:56.596(-3)? (STDERR)     at Module.load (module.js:356:32)
W20160428-17:06:56.596(-3)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160428-17:06:56.597(-3)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 8                        

```

Then I run  ` meteor npm install --save symbol-observable`

                                                
```
daniel@4TW:~/meteor_apps/How-We-Redux-Todos$   meteor npm install --save symbol-observable
npm WARN package.json @ No repository field.
npm WARN unmet dependency /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/react requires fbjs@'^0.8.0' but will load
npm WARN unmet dependency /home/daniel/meteor_apps/How-We-Redux-Todos/node_modules/fbjs,
npm WARN unmet dependency which is version 0.6.1
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "node" "/home/daniel/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "--save" "symbol-observable"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-addons-create-fragment@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-paginate@0.5.7 wants react-addons-create-fragment@^0.14.7

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daniel/meteor_apps/How-We-Redux-Todos/npm-debug.log
```
pls pointMe in some direction :cry:

**Comment by abhiaiyer91** [comment]
Hey there! React Paginate has not upgraded to React 15! So bare with me, either I'll upgrade it for them but hoping they do it themselves

**Comment by michaltakac** [comment]
Try to clone this repo again now and follow quickstart in readme, check back if your issue is resolved.

**Comment by dangaresp** [comment]
```
dage@thebay:~/meteor/How-We-Redux-Todos(master)$ meteor npm install
npm WARN deprecated react-paginate@1.0.5: This version of react-paginate is deprecated and will be removed. If you want to use react-paginate with react v0.14.*, please use react-paginate@1.0.4. If you want to use react-paginate with react@>15.0.0, please use react-paginate@>2.0.0.
npm WARN peerDependencies The peer dependency react-addons-create-fragment@^15.0.1 included from react-paginate will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
react-addons-pure-render-mixin@15.1.0 node_modules/react-addons-pure-render-mixin

react-dom@15.1.0 node_modules/react-dom

classnames@2.2.5 node_modules/classnames

redux-thunk@2.1.0 node_modules/redux-thunk

redux-logger@2.6.1 node_modules/redux-logger

react-addons-create-fragment@15.1.0 node_modules/react-addons-create-fragment

react-paginate@1.0.5 node_modules/react-paginate
└── classnames@1.2.2

redux@3.5.2 node_modules/redux
├── symbol-observable@0.2.4
├── lodash-es@4.13.1
├── lodash@4.13.1
└── loose-envify@1.2.0 (js-tokens@1.0.3)

react-redux@4.4.5 node_modules/react-redux
├── invariant@2.2.1
├── hoist-non-react-statics@1.0.6
├── lodash@4.13.1
└── loose-envify@1.2.0 (js-tokens@1.0.3)

react@15.1.0 node_modules/react
├── object-assign@4.1.0
├── loose-envify@1.2.0 (js-tokens@1.0.3)
└── fbjs@0.8.2 (ua-parser-js@0.7.10, core-js@1.2.6, promise@7.1.1, isomorphic-fetch@2.2.1)
```
```
Unable to resolve some modules:

  "react-mixin" in /home/dage/meteor/How-We-Redux-Todos/imports/client/components/TodoList.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save react-mixin       
```

```
dage@thebay:~/meteor/How-We-Redux-Todos(master)$   meteor npm install --save react-mixin       
react-mixin@3.0.5 node_modules/react-mixin    
├── object-assign@4.1.0
└── smart-mixin@2.0.0
```
```
dage@thebay:~/meteor/How-We-Redux-Todos(master)$ meteor --port 4000
[[[[[ ~/meteor/How-We-Redux-Todos ]]]]]       

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          
                                              
=> App running at: http://localhost:4000/   
```

 thk  michaltakac! ,work great!

**Comment by abhiaiyer91** [comment]
@dangaresp if you want to help out and upgrade `react-paginate` that would be great. Also to get rid of the `react-mixin` dependency?
